# Generated by Django 6.0.6 on 2026-06-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Gérant / Admin'), ('cashier', 'Caissier')], default='cashier', max_length=20),
        ),
    ]
